### ISSUE TITLE
Benq TK700STI examine issue 

### ISSUE THREAD

**Issue by pborsiak** [rrooggiieerr/benqprojector.py#23]
Hi - tried to examine and got that:

root@Wyse:/home/badger# python3 -m benqprojector serial /dev/ttyUSB0 9600 examine                                                                                       Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.7/dist-packages/benqprojector/__init__.py", line 10, in <module>
    from benqprojector.benqprojector import (
  File "/usr/local/lib/python3.7/dist-packages/benqprojector/benqprojector.py", line 393
    elif (response := self._read_response()) == "":
                   ^
SyntaxError: invalid syntax
root@Wyse:/home/badger#

**Comment by rrooggiieerr** [comment]
I'm not running into this syntax error, which version of Python 3 are you using? I'm on 3.12.7
